server:
  port: 9090

spring:
  application:
    name: ACCOUNT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/accountMicroservice?useSSL=false
    username: root
    password: root
  config:
    import: optional:configserver:http://localhost:9093
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
